//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pls.Utils.resource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Messages_CN() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pls.Utils.resource.Messages_CN", typeof(Messages_CN).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与 您的用户已经超过2天没有激活了，不能再激活，请联系管理员 类似的本地化字符串。
        /// </summary>
        public static string ActivationOvertime {
            get {
                return ResourceManager.GetString("ActivationOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 该数据已经禁用，不允许发送 类似的本地化字符串。
        /// </summary>
        public static string AlreadyDisable {
            get {
                return ResourceManager.GetString("AlreadyDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 该数据已存在，不允许插入 类似的本地化字符串。
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 商品优惠信息暂时只能设置一份 类似的本地化字符串。
        /// </summary>
        public static string CouponYesOne {
            get {
                return ResourceManager.GetString("CouponYesOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 超级管理员(admin)不能删除，请不要强制删除 类似的本地化字符串。
        /// </summary>
        public static string DeleteAdmin {
            get {
                return ResourceManager.GetString("DeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您的邮箱已经激活，请不要重复激活 类似的本地化字符串。
        /// </summary>
        public static string EmailActivation {
            get {
                return ResourceManager.GetString("EmailActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 结果为空 类似的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 操作失败 类似的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 存在关联数据，不允许禁用 类似的本地化字符串。
        /// </summary>
        public static string ExistsRelation {
            get {
                return ResourceManager.GetString("ExistsRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 请您选择需要上传的图片 类似的本地化字符串。
        /// </summary>
        public static string ImageNo {
            get {
                return ResourceManager.GetString("ImageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 请您保持邮件原内容请求，您的key值被您改变 类似的本地化字符串。
        /// </summary>
        public static string KeyNoError {
            get {
                return ResourceManager.GetString("KeyNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 邮箱/手机号已被注册，不允许再注册 类似的本地化字符串。
        /// </summary>
        public static string LoginNameEmailPhoneYes {
            get {
                return ResourceManager.GetString("LoginNameEmailPhoneYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您的用户未激活，请登录邮箱激活 类似的本地化字符串。
        /// </summary>
        public static string NoActivation {
            get {
                return ResourceManager.GetString("NoActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 无效的请求地址 类似的本地化字符串。
        /// </summary>
        public static string NoAddress {
            get {
                return ResourceManager.GetString("NoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您没有权限操作超级管理员admin 类似的本地化字符串。
        /// </summary>
        public static string NoAdmin {
            get {
                return ResourceManager.GetString("NoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 用户被禁用，请联系管理员 类似的本地化字符串。
        /// </summary>
        public static string NoDisable {
            get {
                return ResourceManager.GetString("NoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 未知错误 类似的本地化字符串。
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您还没有登录，请您登录 类似的本地化字符串。
        /// </summary>
        public static string NoLogin {
            get {
                return ResourceManager.GetString("NoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您未设置商品版本信息，无法给其商品设置优惠 类似的本地化字符串。
        /// </summary>
        public static string NoSetShopSku {
            get {
                return ResourceManager.GetString("NoSetShopSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您没有入驻此商城，请在个人中心申请入驻 类似的本地化字符串。
        /// </summary>
        public static string NoVisit {
            get {
                return ResourceManager.GetString("NoVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 操作成功 类似的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 原始密码错误 类似的本地化字符串。
        /// </summary>
        public static string OldPwdError {
            get {
                return ResourceManager.GetString("OldPwdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 该订单已处于删除状态，不允许进行此操作 类似的本地化字符串。
        /// </summary>
        public static string OrderAlreadyDelete {
            get {
                return ResourceManager.GetString("OrderAlreadyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 该订单已禁用，不允许进行此操作 类似的本地化字符串。
        /// </summary>
        public static string OrderAlreadyDisable {
            get {
                return ResourceManager.GetString("OrderAlreadyDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 该订单已经支付，不允许禁用 类似的本地化字符串。
        /// </summary>
        public static string OrderAlreadyPay {
            get {
                return ResourceManager.GetString("OrderAlreadyPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 该订单已经发货，不允许禁用 类似的本地化字符串。
        /// </summary>
        public static string OrderAlreadySend {
            get {
                return ResourceManager.GetString("OrderAlreadySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 参数不能为空 类似的本地化字符串。
        /// </summary>
        public static string ParaEmpty {
            get {
                return ResourceManager.GetString("ParaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 参数传递错误 类似的本地化字符串。
        /// </summary>
        public static string ParaError {
            get {
                return ResourceManager.GetString("ParaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 接口异常 类似的本地化字符串。
        /// </summary>
        public static string PortError {
            get {
                return ResourceManager.GetString("PortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 读取数据错误 类似的本地化字符串。
        /// </summary>
        public static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 服务器错误 类似的本地化字符串。
        /// </summary>
        public static string ServerData {
            get {
                return ResourceManager.GetString("ServerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您的优惠金额比实际上的金额还高，无法录入，请检查 类似的本地化字符串。
        /// </summary>
        public static string ShopCouponMaxCurrentMoney {
            get {
                return ResourceManager.GetString("ShopCouponMaxCurrentMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 商品会员价不可以比商品的原价还高，请您检查修改 类似的本地化字符串。
        /// </summary>
        public static string ShopCurrentMaxOriginal {
            get {
                return ResourceManager.GetString("ShopCurrentMaxOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您上传的格式不正确，请您选择正确的格式上传 类似的本地化字符串。
        /// </summary>
        public static string ShopImageExtion {
            get {
                return ResourceManager.GetString("ShopImageExtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您上传的图片尺寸已经超过了1M，请处理之后再上传 类似的本地化字符串。
        /// </summary>
        public static string ShopImageMax {
            get {
                return ResourceManager.GetString("ShopImageMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您的商品SKU设置图片已经超过4张，最多限制只能上传4张 类似的本地化字符串。
        /// </summary>
        public static string ShopSkuImageYesThree {
            get {
                return ResourceManager.GetString("ShopSkuImageYesThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 该类型的角色数据已存在，不允许插入 类似的本地化字符串。
        /// </summary>
        public static string TypeAlreadyExists {
            get {
                return ResourceManager.GetString("TypeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您选择的版本低于您所购买的版本，不需要升级 类似的本地化字符串。
        /// </summary>
        public static string UpgradeError {
            get {
                return ResourceManager.GetString("UpgradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 用户名或密码错误 类似的本地化字符串。
        /// </summary>
        public static string UserPwdNoError {
            get {
                return ResourceManager.GetString("UserPwdNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 此数据您已经处理过，不允许在处理 类似的本地化字符串。
        /// </summary>
        public static string YesHandle {
            get {
                return ResourceManager.GetString("YesHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 您的商品已配置属性，不允许再配置，如需修改，请您去修改模块修改 类似的本地化字符串。
        /// </summary>
        public static string YesSetAttrForShop {
            get {
                return ResourceManager.GetString("YesSetAttrForShop", resourceCulture);
            }
        }
    }
}
